### ISSUE TITLE
Split out LESS into a core package

### ISSUE THREAD

**Issue by dcousens** [elementalui/elemental#1]

**Comment by dcousens** [comment]
@jossmac could this be done in such a way that theming is easily possible for an end user?

**Comment by jossmac** [comment]
Could you expand on this a bit?

**Comment by jossmac** [comment]
Ref #30 for discussion related to styles in components

**Comment by LorbusChris** [comment]
Continuing the inline styles discussion:
Maybe JSS is worth being looked at for having (namespaced) rules, that might also be used to do the theming @dcousens mentioned. In that case deprecating LESS, though.

**Comment by LorbusChris** [comment]
didn't see #53 react-jss @kof cool!

**Comment by jossmac** [comment]
No longer relevant. Ref #53
