### ISSUE TITLE
Dropdown menu scroll behaviour

### ISSUE THREAD

**Issue by jossmac** [elementalui/elemental#10]
At the moment when you get reach the scroll threshold (top/bottom) you begin to scroll the body, or the nearest scrollable parent. It'd be nice to trap the scroll inside the dropdown menu.

Perhaps something like http://codepen.io/somethingkindawierd/blog/react-mixin-scroll-lock

**Comment by JedWatson** [comment]
I'm not totally convinced it should behave like that... seems like a bad idea to block page scrolling over a menu to me. Let's experiment with it and see how it feels.

**Comment by LorbusChris** [comment]
How about scrolling the part over which mouse is hovering? When over a dropdown, scroll dropdown, when over scrollable parent (like app body), scroll parent.

**Comment by rstormsf** [comment]
How about provide it as an optional boolean value?
