### ISSUE TITLE
How do I override constants?

### ISSUE THREAD

**Issue by lwansbrough** [elementalui/elemental#105]
I want to permanently change the gutter width. This is fairly trivial on the LESS side, however overriding the constants.js file seems impossible without modifying the source code.

**Comment by jossmac** [comment]
@lwansbrough thanks for raising this. Elemental will likely receive a major overhaul soon, which makes it tricky to spend time on this sort of thing.

For now I recommend creating a component in your repo that renders Elemental's `Container` with the values you desire.
