### ISSUE TITLE
Modal: Content moves to the right in Windows browsers

### ISSUE THREAD

**Issue by slider23** [elementalui/elemental#107]
This problem have almost all early versions scripts of modal windows. In Windows (not Mac) after launch modal window content under modal window moves to the right. Root of problem - scrollbar in Windows have 15px, scrollbar in Mac - 0px.

![modal_window_elemental_ui](https://cloud.githubusercontent.com/assets/142277/11805008/92ce9984-a319-11e5-893c-c13ea971448b.gif)

Same issues in Twitter Bootstrap: https://github.com/twbs/bootstrap/issues/9886 , https://github.com/twbs/bootstrap/issues/9855 . In 3.3.2 problem was solved.

**Comment by tomasvarg** [comment]
I confirm this behavior on Chrome/Chromium & Firefox, Linux & Win 10; seems like it was tested only on one browser. Another issue is it displays two scrollbars at one moment (as can be seen on the gif).  Probably caused by a hacky usage of modal's wrapper element.

**Comment by jossmac** [comment]
@slider23 nice catch! @tomasvarg. Thanks for the browser information.
