### ISSUE TITLE
`data-uri` causes build system (webpack) to fail

### ISSUE THREAD

**Issue by samzhao** [elementalui/elemental#11]
First of all, I regret not discovering this amazingly well-written library/toolkit earlier, so thanks for putting this together :) And I wouldn't mind writing documentations for it in my spare time.

I had a problem with `data-uri` with webpack style loaders where the path fails to resolve. Also, I read somewhere that data uris actually load slower than directly referencing the asset paths. Therefore, it would be nice to remove the 2 data-uri usages if we could unless there's some considerations that I'm not aware of.

Thanks!

**Comment by JedWatson** [comment]
@samzhao thanks! would be great to have you help write documentation, I'll set up gitter shortly for Elemental so we can chat about it. @jossmac has been making the examples but we need to add code snippets for them, and document the various options that are supported.

We're using `data-uri` to get around needing to ship public assets, which are difficult to wrap up in a way that works across all build processes. Would you be able to share a github repo with a simple setup including elemental and a web pack config that I can clone to reproduce the error?

**Comment by samzhao** [comment]
@JedWatson The project I'm currently working on is unfortunately not open source, but here is a slightly simplified version of it: https://github.com/samzhao/elemental-webpack.

Let me know when you have gitter setup and maybe put together a documentation format to follow :)

**Comment by samzhao** [comment]
When you clone the project and run it locally by doing `npm start`, you should see something like this:

![screen shot 2015-05-30 at 1 51 47 pm](https://cloud.githubusercontent.com/assets/1125203/7899320/87a71230-06d3-11e5-8399-2296dc916a6f.png)

**Comment by JedWatson** [comment]
Thanks @samzhao, I'll clone that and take a look.

@petehunt @mjackson @zackify @nmn this issue is pretty relevant to the conversation we were just having on the podcast :) would love pointers if you have them.

**Comment by soupaJ** [comment]
FYI, this sounds related to the issue @sokra mentioned here https://github.com/webpack/less-loader/issues/43#issuecomment-96580193

**Comment by ivan-kleshnin** [comment]
Can we just replace this `data-uri` with `url` and put a comment to come back to this later when LESS loader will be fixed?!

**Comment by ericclemmons** [comment]
This is missing a tagged release to work correctly with Webpack :) (`v2.0.0` is the latest)

**Comment by JedWatson** [comment]
@ericclemmons sorry about that, I've just pushed a new release (`v0.2.1`) with @jossmac's fix in it!

**Comment by ericclemmons** [comment]
:steam_locomotive: WoOt WoOt! :steam_locomotive:

**Comment by samzhao** [comment]
Fix confirmed. Thanks @JedWatson and @jossmac!
