### ISSUE TITLE
Button dropdown box flickers when closing

### ISSUE THREAD

**Issue by LinkTree3** [elementalui/elemental#110]
I tested this in firefox and chrome and this happens only in chrome.
When clicking on one of the options in the dropdown or on the button itself to close the menu, the menu closing animation rapidly flickers until it closes instead of closing smoothly.

**Comment by zenorocha** [comment]
+1

**Comment by HriBB** [comment]
+1 on Nexus7

**Comment by zsherman** [comment]
+1

**Comment by aberg-bit9** [comment]
+1

**Comment by jossmac** [comment]
Resolved by #207
