### ISSUE TITLE
Col padding causes issues.

### ISSUE THREAD

**Issue by Tackyshot** [elementalui/elemental#112]
Because of the fixed padding for the Columns (10px default) there are styling issues when it comes to specifying your widths. Columns should be padding and margin free.

**Comment by jossmac** [comment]
Row and Col both accept the property `gutter`, which is defaulted to `20px`. It'd be nice if this could be defined once in the consumer app and possibly passed down through context.

@Tackyshot you can use the prop to set your gutter right now

@JedWatson thoughts on defaulting through context?

**Comment by Tackyshot** [comment]
is there any documentation? because for the life of me I can't seem to find it.

**Comment by jossmac** [comment]
Sorry @Tackyshot! Just realised that it's undocumented atm.

For handling the grid `col`:
```
basis:
	number, // pixels
	string  // percentage
gutter: number
lg: string // width as a percentage or fraction
md: string // width as a percentage or fraction
sm: string // width as a percentage or fraction
xs: string // width as a percentage or fraction
```
With `row` only gutter is important
