### ISSUE TITLE
Ally.js seems to be a pre-built javascript file

### ISSUE THREAD

**Issue by biznickman** [elementalui/elemental#119]
I'm using elemental UI in a webpack project and I'm getting the following error:

`This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/elemental/~/ally.js/ally.min.js 2:412-419`

Any ideas how to resolve this?

**Comment by JedWatson** [comment]
I've just pushed a new version `0.5.11` that disables the `ally` integration until we can review it more thoroughly, there have been a number of issues related to it. See my last comment on #108 for the full story.
