### ISSUE TITLE
getting started?

### ISSUE THREAD

**Issue by dcsan** [elementalui/elemental#121]
is there a getting started guide anywhere? 
what do i need to do to include this project?

Ideally i don't want to introduce bower etc to my toolchain, but I don't see a /dist/ folder I can just add to a project...

**Comment by NogsMPLS** [comment]
FYI, there is an issue for a getting started page for the repo already. I have answered, to the best of my current knowledge, your questions here:

https://github.com/elementalui/elemental/issues/74#issuecomment-172232332

**Comment by jossmac** [comment]
Resolved by #153
