### ISSUE TITLE
Website Example: Dropdown Broken

### ISSUE THREAD

**Issue by ppiekarczyk** [elementalui/elemental#13]
http://elemental-ui.com/forms

Under `Validation`, selecting an item in the dropdown will not change the state of the dropdown, but a validation error will appear.

**Comment by AlexKVal** [comment]
Should this issue be closed now ?

**Comment by ppiekarczyk** [comment]
Still doesn't work under `Validation`

**Comment by AlexKVal** [comment]
It seems the site hasn't been updated yet because there was no any release.

**Comment by jossmac** [comment]
Will publish a new version to npm and update the website today when I have a chance

**Comment by JedWatson** [comment]
Released on the weekend, I've verified it's fixed. Thanks!
