### ISSUE TITLE
Thoughts on moving testings into src directory

### ISSUE THREAD

**Issue by cameronroe** [elementalui/elemental#132]
It doesn't seem like there's a ton of tests covering the components. Was just curious of what your thoughts would be on moving the tests into the components directory with a `.spec.js` before you started writing more. Ideally you could use [enzyme](https://github.com/airbnb/enzyme) with mocha and just point to `src/**/*.spec.js`. This would keep everything together and it might be easier to see which specs are missing.

**Comment by jossmac** [comment]
@cameronroe Enzyme would be perfect for this project. Unfortunately we're time-poor atm.

Please bump this issue if you're interested in submitting a PR 🙂
