### ISSUE TITLE
blacklist?

### ISSUE THREAD

**Issue by piehouserat** [elementalui/elemental#138]
Hey guys,

I'm very new to React and the way it works and was just wondering what is the purpose of using blacklist?

Cheers,
Martin

**Comment by jossmac** [comment]
Often when creating components in React you want to pass all (or most) props down to a child. When rendering form fields etc. some props often conflict with the node's own `attr`. [blacklist](https://www.npmjs.com/package/blacklist) is a tidy solution for this

**Comment by piehouserat** [comment]
Thanks for the answer, makes sense :)
