### ISSUE TITLE
Update octicons

### ISSUE THREAD

**Issue by zenorocha** [elementalui/elemental#139]
Right now, elemental uses v3.1.0 while the latest version of octicons is v3.5.0. Can we get this updated?

**Comment by jossmac** [comment]
Sounds good, would you mind submitting a PR?

**Comment by jacargentina** [comment]
@jossmac My PR #146 was just that (updating octicons to 3.5.0) but it was rejected by @mxstbr 

I would love that rejection to be undone, and update octicons.

**Comment by mxstbr** [comment]
We can't merge the octicons update I'm afraid, see https://github.com/keystonejs/keystone/pull/2508#issuecomment-200651590.

**Comment by jossmac** [comment]
@jacargentina octicons don't follow semver - @mxstbr rejected the PR at my request. Sorry mate, but we can't have icons suddenly disappearing from consumer's apps and websites.
