### ISSUE TITLE
Accordion / Collapse Component

### ISSUE THREAD

**Issue by jeffreypriebe** [elementalui/elemental#143]
Any plans to create an accordion / collapse component?
(E.g. [Bootstrap collapse accordion](http://getbootstrap.com/javascript/#collapse-example-accordion))

**Comment by nkbt** [comment]
Have you tried react-collapse?

**Comment by jeffreypriebe** [comment]
Sure haven't. Is the developer any good? ;)

I'm more thinking something in the elemental-ui style, not simply a react-based collapse.

**Comment by nkbt** [comment]
`react-collapse` is a `base`-sort of component. It has no extras. You can create some styled accordion and make a PR here to elemental-ui ;)

**Comment by jeffreypriebe** [comment]
Normally, I'd just submit a PR here, but I don't have the time currently, and was just wondering what their plan was. Still wondering...

**Comment by nkbt** [comment]
If we get to implementing something like that for our project it will
definitely land here. I am not very keen on creating libs that I do not use
personally - that way does not really work well. Maybe someone else is
interested in landing this feature?

PS: bear in mind I am talking just as a random contributor here, not from
the position of elemental-ui team.

**Comment by jossmac** [comment]
@jeffreypriebe please bump this issue if you're still interesting in submitting a PR 🙂
