### ISSUE TITLE
FormSelect arrows height issue

### ISSUE THREAD

**Issue by tzvigqb** [elementalui/elemental#148]
Using the form components exactly as shown in the docs, the arrows are not vertically aligned, as shown below. The arrows span get their height from line-height, which does not seem to be taking affect here. Nothing is being overrode in the styles in devtools. Any ideas?
![forminput](https://cloud.githubusercontent.com/assets/8038821/14049194/eea96b3e-f289-11e5-88b2-5b08205bafff.jpg)

**Comment by kuy** [comment]
@tzvigqb Do you have gist snippet or reproducible code?

**Comment by jossmac** [comment]
@tzvigqb please provide reproducible example and browser information. Will re-open when applicable.
