### ISSUE TITLE
Unable to use UI elements

### ISSUE THREAD

**Issue by purezen** [elementalui/elemental#151]
Hi, I am making a React app and want to use elemental for the ui part.
The `Col` and `Row` elements are working fine, but when I try to use any UI element like `Alert` or `Card` or `Pill`, they miss their styling completely.
For example when I use a `Pill`, I can only see a button.

**Comment by DarrylD** [comment]
+1. Having the same issue

**Comment by purezen** [comment]
@DarrylD it's because you have not included the styling (less) file in your code. Just import the less file in your root app file using
`import '../node_modules/elemental/less/elemental.less'`

and add this in your webpack config
```
{
  test: /\.less$/,
  loader: "style!css!less"
}
```
