### ISSUE TITLE
Modeling APIs after jQuery UI widgets

### ISSUE THREAD

**Issue by cameronroe** [elementalui/elemental#152]
http://devdocs.io/jqueryui-widgets/

Rather than re-inventing the wheel, jQuery UI has a number of widgets that are built with 3 things:
1. options
2. methods
3. events

Obviously, not everything will transfer over because React makes things a lot easier, but I think it could be beneficial to examine some of these widgets for their naming. For example, they have a autocomplete widget with certain options and it might be useful to port some of those into elemental.

Just an idea, but thought I'd post it.

**Comment by jossmac** [comment]
@cameronroe interesting idea, not really on the roadmap though, i'm afraid.
