### ISSUE TITLE
FileUpload event should be persisted

### ISSUE THREAD

**Issue by jacksonrayhamilton** [elementalui/elemental#156]
In the FileUpload `handleChange` method, the "event" object (`e`) is [referenced asynchronously](https://github.com/elementalui/elemental/blob/40619acebdd8aeccbf8adfcefe6c276f6bb73bb3/src/components/FileUpload.js#L55). But, per [React's documentation](https://github.com/facebook/react/blob/fef495942a1cf7d507c816192fde205b6003df05/docs/docs/ref-05-events.md#event-pooling),

> If you want to access the event properties in an asynchronous way, you should call `event.persist()` on the event, which will remove the synthetic event from the pool and allow references to the event to be retained by user code.

If `event.persist()` is not called, then errors can occur when using the object. In particular, this prevents the component from being usable with the `redux-form` library.

Fixing this would probably be as simple as calling `e.persist()` in the first line of `handleChange`.

**Comment by jossmac** [comment]
@jacksonrayhamilton thanks for raising this issue. Would you mind investigating, and potentially creating a PR?

**Comment by jacksonrayhamilton** [comment]
Sorry @jossmac, but I will not at this time, as I'm no longer using this library.

**Comment by jossmac** [comment]
No worries, thanks for getting back to me.
