### ISSUE TITLE
backdropClosesModal doesn't seems to close the modal

### ISSUE THREAD

**Issue by dcaillibaud** [elementalui/elemental#159]
Hi,

I understand that the backdropClosesModal prop should close modal on click outside the modal, but it doesn't seem to do so in your live demo on http://elemental-ui.com/modal, so I'm wondering if I misunderstand it or if it's a bug…

Thanks

**Comment by purezen** [comment]
Yeah, it is not working for me in the app too.

**Comment by rntdrts** [comment]
+1

**Comment by cwmacdon** [comment]
I've made a PR #181 to fix this issue.

**Comment by jossmac** [comment]
I'm sorry for the inconvenience @dcaillibaud @purezen  @rntdrts -- should have caught this sooner.

Resolved by #206
