### ISSUE TITLE
Need help using the library

### ISSUE THREAD

**Issue by purezen** [elementalui/elemental#162]
Hi,

Thanks for the amazing library! It has helped me get started with my personal project at [link](https://purezen.github.io/story-app).

However, I have been facing a couple of issues with it:
- The webapp currently doesn't scale for mobile devices.
  I.e. it scales fine on the desktop but when I access the site in a mobile browser.. I see the same page.
- I am unable to use the full-page Spinner component as intended using `<Spinner size='lg' />`
  Right now it appears in the top-left corner.
- I am currently using `Row` and `Col` components to implement the grid in my app.
  The way I am centring the content right now is

```
<Row>
  <Col md='1/4'><Col/>
  <Col md='2/4'><Col/>
    <ContentToRender />
  <Col md='1/4'><Col/>
<Row/>
```

Not using any CSS atm.
Is this the correct way? Can the `Container` component be of use?

Not sure if this is the best place to ask. Would be glad to have any sort of help here.
Thanks!

**Comment by Garretttaco** [comment]
@purezen This sounds like it is not an issue with the library. This is a feature that a specific meta tag adds.Here is the tag. Place this in the head of your index file `<meta name="viewport" content="width=device-width, initial-scale=1">`

Hope this helps!

**Comment by purezen** [comment]
@Garretttaco Hey, thanks there. I used the meta tag in my app and now it does indeed scale for mobile devices!
Thanks there 👍 

Right now the `Spinner` still appears at the top-left corner of the page when I use it. I would like to get it in the middle of the app while being compatible on mobile devices. What would be the recommended way to achieve that?
