### ISSUE TITLE
Difference between /lib and /src

### ISSUE THREAD

**Issue by Elesant** [elementalui/elemental#17]
Hey sorry guys, this might be a dumb question, but what is the difference between the code in /lib and the /src folder? Thanks! :)

**Comment by JedWatson** [comment]
The `/src` is the actual source, `/lib` is the _transpiled_ version generated by Babel that gets used when you `require('elemental')` in your project. We should (probably) exclude `lib` from the git repo to reduce confusion, need to lock down our build & release process first though.

We'll explain this with a contributing file shortly (#14) but in the meantime if you contribute, please make sure you only include changes to `/src` in your PR!
