### ISSUE TITLE
Disabled option tag in FormSelect component

### ISSUE THREAD

**Issue by kuy** [elementalui/elemental#177]
I'm using `FormSelect` component in my app, but I can't find props to disable the last option.
Here is an example code what I want to do.

```
const opts = {
  { label: 'A', value: 'a' },
  { label: 'B', value: 'b' },
  { label: 'C', value: 'c', disabled: true },
};

// ...

<FormSelect options={opts} />
```

Is there anyone working on this? If not, I'd like to tackle.

**Comment by jossmac** [comment]
@kuy good catch! PR would be appreciated :)

**Comment by kuy** [comment]
@jossmac Thanks for merging! I'll one more PR for updating documentation.

**Comment by chexers** [comment]
Eereerrreeeeeeeeeeeeeeeeereeeeeeereeee
On Sep 13, 2016 1:05 AM, "Yuki Kodama" <notifications@github.com> wrote:
>e
> @jossmac Thanks for merging! I'll one more PR for updatinge
documentation.eeeeeeeeeeereeerreeeeeereeeeeeeeeeeeeeeeeeeereeeeeeeeeeeeeeeeeereeeeeeeeeeeereeeeeeeeeeeeeeeeeeeeereE

**Comment by chexers** [comment]
Eereerrreeeeeeeeeeeeeeeeereeeeeeereeee
On Sep 13, 2016 1:05 AM, "Yuki Kodama" <notifications@github.com> wrote:
>e
> @jossmac Thanks for merging! I'll one more PR for updatinge
documentation.eeeeeeeeeeereeerreeeeeereeeeeeeeeeeeeeeeeeeereeeeeeeeeeeeeeeeeereeeeeeeeeeeereeeeeeeeeeeeeeeeeeeeereE

**Comment by jossmac** [comment]
@chexers are you okay? It looks like you passed out on your keyboard...
