### ISSUE TITLE
Modal breakes data flow for Redux

### ISSUE THREAD

**Issue by kapooostin** [elementalui/elemental#184]
Redux `connect()` fails to find `store` for a container element if it is rendered inside `<Modal>` component.

**Comment by jossmac** [comment]
Could be an issue with `context` not being passed through because of the `<Portal />`, which wraps the Modal component.

You may need to explicitly pass the context - check out http://stackoverflow.com/a/30372606/2305750

**Comment by kapooostin** [comment]
Yes, it is an issue with `context`. My first attempt to add wrapping component to pass parent context failed. But passing `store` as a prop did help.

**Comment by kapooostin** [comment]
Well, actually I did exactly what was suggested on OS. At first I decided that I should wrap `<Modal>` and this didn't work. But if I restore `context` for **contents** of `<Modal>` by wrapping it in a component that sets its children context from a passed prop, everything seems to be OK.

```jsx
import React, { Component, PropTypes } from 'react'

class ShowModal extends Component {
  static contextTypes = {
    store: PropTypes.object
  }

  render () {
    return (
      <Modal>
        <ModalBody>
          <WithContext { ...this.context } />
        </ModalBody>
      </Modal>
    )
  }
}

class WithContext extends Component {
  static propTypes = {
    store: PropTypes.object.isRequired
  }

  static childContextTypes = {
    store: PropTypes.object.isRequired
  }

  getChildContext () {
    return {
      store: this.props.store
    }
  }

  render () {
    return { this.props.children }
  }
}
```
