### ISSUE TITLE
Bug in install guide on home page.

### ISSUE THREAD

**Issue by tbillington** [elementalui/elemental#187]
On https://elemental-ui.com/home there in an instruction to compile the styles if your project will not have a less compiler. The instruction says

```
npm install -g less 
lessc --clean-css ./node_modules/elemental/less/elemental.less styles.min.css 
```

However, this fails with:

```
> lessc --clean-css ./node_modules/elemental/less/elemental.less styles.min.css
Unable to interpret argument clean-css - if it is a plugin (less-plugin-clean-css), make sure that it is installed under or at the same level as less
```

To remedy, `less-plugin-clean-css` must also be installed.

```
npm install -g less-plugin-clean-css
```

Now the previous compile command will succeed.

**Comment by jossmac** [comment]
Resolved by #189
