### ISSUE TITLE
How to use context inside a modal?

### ISSUE THREAD

**Issue by hl-a-k** [elementalui/elemental#194]
I put a redux form in an Elemental Modal:   
`<Modal isOpen={modalIsOpen} backdropClosesModal>
        <TradeForm1 onSubmit={this.handleSubmit} />
      </Modal>`
get an error:
browser.js:40 Uncaught Invariant Violation: Could not find "store" in either the context or props of "Connect(Form(TradeForm))". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Form(TradeForm))".

**Comment by jossmac** [comment]
Hi @hl-a-k,

Thanks for using Elemental!

This is one of the problems with using `context` I'm afraid. Our modal component uses a "portal" ([great explanation + code on StackOverflow](http://stackoverflow.com/a/28823590/2305750)) allowing it to be rendered outside of its parent, in our case as the last element before close of body.

Unfortunately this takes it out of React's parent --> child relationship, which it relies on for `context`. We can circumvent the issue by using an intermediary component to pass the context onto the child[ren].

Please see my [`<PassContext />` component](https://github.com/jossmac/react-images/blob/master/src/components/PassContext.js) (ignore `childContextTypes/theme`, that's repo specific) and an example implementation:

```jsx
<PassContext>
  <Modal>
    <TradeForm1 onSubmit={this.handleSubmit} /> 
  </Modal>
</PassContext>
```

Thanks for raising this, its obscure nature has likely caught a few people.

Let me know how you go 😄

**Comment by hl-a-k** [comment]
I copied PassContext into my project:
`
class PassContext extends React.Component {
  getChildContext () {
    return this.props.context;
  }
  render () {
    return Children.only(this.props.children);
  }
};
PassContext.propTypes = {
  context: PropTypes.object.isRequired,
};
`
but I got another error:
`Uncaught Invariant Violation: PassContext.getChildContext(): childContextTypes must be defined in order to use getChildContext()`

Thanks your reply🙂

**Comment by jossmac** [comment]
@hl-a-k sorry mate, got caught up in the theme implementation of that codebase. You _will_ have to define the `childContextTypes` that redux form is expecting.

**Comment by hl-a-k** [comment]
I did some change:
` <PassContext context={this._reactInternalInstance._context}>
        <ContactForm1 onSubmit={this.handleSubmit} />
        </PassContext>`
`PassContext.childContextTypes = {
  store: PropTypes.object,
  storeSubscription: PropTypes.object,
  "@@contextSubscriber/router": PropTypes.object,
  "router":PropTypes.object,
};`

then the form can work in the Modal

**Comment by jossmac** [comment]
Great!
