### ISSUE TITLE
Dropdown flicker

### ISSUE THREAD

**Issue by ShashankaNataraj** [elementalui/elemental#196]
[The buttons section ](**http://elemental-ui.com/buttons**) in the docs has a dropdown section. Clicking on the default trigger and then dismissing it by clicking somewhere else causes the dropdown shown to flicker and then dismiss itself.

**Comment by clschnei** [comment]
Can you reproduce and post gif/video link?

**Comment by dadocolussi** [comment]
Here is a video: [dropdown-flicker.mov.zip](https://github.com/elementalui/elemental/files/1259000/dropdown-flicker.mov.zip)

**Comment by jossmac** [comment]
Related to #204
