### ISSUE TITLE
Get rid of the lib folder except for npm

### ISSUE THREAD

**Issue by JedWatson** [elementalui/elemental#20]
To reduce confusion, we should probably not include the build folder `/lib` in the Git repo (#17)

Before we do, we need to make sure the release process _absolutely always_ generates `lib` from the latest `src` so we don't accidentally push out a dev (or worse, missing) build folder. At the moment, the git workflow makes it pretty obvious so that hasn't been a problem,

We'll also want to explain how to build your own if you download the repo, that should probably go in the Readme, and explain how to use elemental in `npm link` mode (with `npm run watch`).

**Comment by nkbt** [comment]
if you add `prepublish: 'npm run build'` it will do everything properly. So it is completely safe to exclude `lib` from git. Also it is good to add `.npmignore` and do not ship sources/test/etc.
