### ISSUE TITLE
Support for React v16

### ISSUE THREAD

**Issue by wookiem** [elementalui/elemental#200]
Is there a dev branch that supports React v16 (currently alpha v6)?

Current releases of elemental have a dependency on react-addons-css-transition-group which is deprecated in React v16 in favor of react-transition-group.

The required changes are very minor, but they are breaking changes with React v15:

```
import CSSTransitionGroup from 'react-transition-group/CSSTransitionGroup' // ES6
var CSSTransitionGroup = require('react-transition-group/CSSTransitionGroup') // ES5 with npm
```

It looks like impacts only Dropdown.js and Modal.js.

**Comment by jossmac** [comment]
@wookiem would love a PR for this 🙂

**Comment by jduthon** [comment]
Just did a PR here : https://github.com/elementalui/elemental/pull/214

Let me know if you see any changes.

I also notice some broken stuff on a bunch of components, will make another PR for those fixes.

**Comment by annarichardson** [comment]
When are the new changes to work with React 16 going to be updated to npm?

**Comment by midnightcodr** [comment]
npm still has 0.6.1 as the current version, when will the 0.7.0 version be published to npm?

**Comment by moklick** [comment]
Hey, could you please publish the current version to npm?
