### ISSUE TITLE
<Modal> animation tends to flicker after closing

### ISSUE THREAD

**Issue by LMS007** [elementalui/elemental#204]
http://elemental-ui.com/modal

It does not happen after each time, but seems to be about 50% of the time. It flashes dark and then light again which causes a really unpleasant UX.

I'm running Chrome v60

**Comment by LMS007** [comment]
The issue specifically might be related to Modal.js


```
_react2['default'].createElement(
				TransitionPortal,
				{ transitionName: 'Modal-background', transitionEnterTimeout: 140, transitionLeaveTimeout: 240, component: 'div' },
				this.renderBackdrop()
			)
```

The `transitionLeaveTimeout` value seems to be causing the issue. Lowering the value slightly seems to fix it. I think we need to ensure that the CSS animations finish otherwise these flicker side effects may occur?

The `Modal-background-leave" css class also has a `animation-duration` of 240ms. I'm guessing if these are not perfectly in sync then we see the issue? Lowering the value `transitionLeaveTimeout` value to 200 seems to work much better.

**Comment by jossmac** [comment]
Replacing the animation with a transition will resolve the issue, if anyone would like to pick this up.

https://github.com/elementalui/elemental/blob/master/less/components/Modal.less#L50
