### ISSUE TITLE
Date Picker broken in demo

### ISSUE THREAD

**Issue by nconroy** [elementalui/elemental#21]
The arrow buttons do nothing for me on http://elemental-ui.com/date-picker 
Also in the last picker selecting one of the preset ranges(e.g. Past Week) does nothing.

I am using Chrome

**Comment by JedWatson** [comment]
Hi @nconroy, that component is the last one we've got to get finished before Elemental is ready for use... sorry if it wasn't clear that it isn't complete yet! Hoping to release this week coming.
