### ISSUE TITLE
Doesn't work with React 16

### ISSUE THREAD

**Issue by annarichardson** [elementalui/elemental#216]
When are you updating to be compatible with React 16?

**Comment by jossmac** [comment]
Hi @annarichardson,

Does #214 resolve your issue?

**Comment by annarichardson** [comment]
@jossmac when are these changes being updated to npm?

**Comment by midnightcodr** [comment]
@jossmac 0.6.1 is the version on npm while the master branch is on 0.7.0.

**Comment by jossmac** [comment]
Sorry folks!

@JedWatson could you please publish a new version to npm?
