### ISSUE TITLE
 Modal box is opened out of screen

### ISSUE THREAD

**Issue by nkbt** [elementalui/elemental#24]
![date-ranges](https://cloud.githubusercontent.com/assets/175264/8072475/8eecb1a6-0f59-11e5-86da-435ab11b7541.gif)

**Comment by JedWatson** [comment]
We'll need to detect the current scroll position & viewport size and manually control the position of the modal based on that. Interested in making a PR @nkbt?

**Comment by nkbt** [comment]
@JedWatson yeah, will do that, np

**Comment by nkbt** [comment]
Found that modal box on Datepicker page is a different one. But `elemental` still had the issue

**Comment by jossmac** [comment]
This can be solved with CSS only, hold on a sec. Will submit a fix

**Comment by nkbt** [comment]
@jossmac please, don't solve it css-only. It is a common mistake heaps of people do, which gives enormous pain for end-users.

**Comment by jossmac** [comment]
Okay, would you mind explaining some of the benefits of using JS over CSS for this problem?

**Comment by nkbt** [comment]
From https://github.com/elementalui/elemental/commit/cb8ed70bd3454a4a7de9d1fae904d5a47397ba5d#commitcomment-11624057

> Pretty often modal box is larger then a screen, so one would never get the full content. Using JS approach looks much safer to me.

It is especially painful when you use your phone. Site usually becomes 100% unusable. Could be changed with media queries though, but still the issue will exist and you won't be able to predict all possible screen sizes (compared to content size).

This is why safer approach is not to use `position:fixed`.

**Comment by jossmac** [comment]
Granted I missed it on the first pass - but you can fix this easily by applying an `overflow:auto` to the wrapper, in our case `.Modal`

If that is our only concern I'm not sure we should handle this with JS. It's not so much the initial positioning that concerns me but the constant _repositioning_ even if we debounce.

**Comment by nkbt** [comment]
`overflow:auto` does not give the best experience since you will have scrollbar inside the modal and not the normal usual scrollbar. With all minor experience flaws that multiple scrollbars give you. It is a quick patchy solution that works though.

Repositioning is actually pretty okay if done well. It should support normal scrolling with minimum disruptions. It is quite optional. I can quickly do it today so you can see how it feels.

**Comment by jossmac** [comment]
That'd be terrific, thanks @nkbt
