### ISSUE TITLE
Do we need Modal to follow scroll?

### ISSUE THREAD

**Issue by nkbt** [elementalui/elemental#26]
I reckon we could add an option for Modal to follow scroll. To some extend, of course, so it is possible to scroll if Modal is very long. So if I scroll up after showing modal, it should smoothly follow still having `100px` top margin. If I scroll down - it will follow only if bottom margin is `>=100px`.

If modal is longer then screen, it should follow up, but then will follow down only after bottom margin will be large enough (100px with current styles).

Using setTimeout/clearTimeout to check current scroll every, to say, `200ms`. Not `scroll` event.

![modal-scroll](https://cloud.githubusercontent.com/assets/175264/8081609/807fccc4-0fb9-11e5-91f3-1ff6766090a3.gif)

**Comment by jossmac** [comment]
Any word on this @nkbt?

**Comment by nkbt** [comment]
Ouch!

Sorry, I completely missed this one. Could you please assign the issue to
me, so I won't lose it again?

Thanks.

**Comment by jossmac** [comment]
@nkbt no worries! Thank you for your contributions so far

Just need you to accept your invite to the "collaborators" team so I can assign this is issue to you

**Comment by nkbt** [comment]
Cool, thanks

**Comment by JedWatson** [comment]
ping @nkbt

**Comment by nkbt** [comment]
@JedWatson ouch, time flies... Will get back to this asap!

**Comment by nkbt** [comment]
Added PR #31
