### ISSUE TITLE
Had to copy "spinner.less" to "Spinner.less" on Debian

### ISSUE THREAD

**Issue by lautjy** [elementalui/elemental#28]
Got this error on Debian Jessie when using *elemental*:

    Error: './components/Spinner.less' wasn't found

Fixed it with this:

    cp node_modules/elemental/less/components/spinner.less node_modules/elemental/less/components/Spinner.less

Perhaps change of filename, or change code to use the lowercase name?

**Comment by jossmac** [comment]
Resolved by 7255a9f
