### ISSUE TITLE
Problems at elemental installation

### ISSUE THREAD

**Issue by TCMiranda** [elementalui/elemental#30]
Guys, why is it so difficult to install your package?

First, I had to include the elemental.less in my main, because the components doesn't style itself.
Then I had to require react-date-select, because you hadn't installed
Now, i am at:
"Module build failed: error evaluating function `data-uri`: Cannot 'resolveSync' because the fileSystem is not sync. Use 'resolve'!"

Using webpack, with less-loader and babel-loader

Why dont require styles at the component?

**Comment by nkbt** [comment]
Hi, @TCMiranda you basically just named our major concerns about assets. We have just discussed those yesterday and hopefully they will be resolved soon.
Including styles in the component itself has some implications. There is an issue opened asking for the opposite thing #1 =)

**Comment by TCMiranda** [comment]
Hi @nkbt 

Thanks very much, I can see, so, my opinion
 
I think that it is great to offer the styles when you are building some ui package, really makes sense, but the components are raw without requiring css

As in ReactJS [Why React](https://facebook.github.io/react/docs/why-react.html)
> Build Composable Components
React is all about building reusable components. In fact, with React the only thing you do is build components. Since they're so encapsulated, components make code reuse, testing, and separation of concerns easy.

Another example is Polymer, which follows principles of web components, reusable and self-contained, defining the HTML, CSS and JS inside the component

The css "bootstrap" may be a great feature, but the components are something else, i can't find a reason to not make them work out of the box.

In my projects i follow the structure (with stylus, but could be less)

1. core.styl -> Used by components (doesn't print anything)
  * Variables -> Colors, sizes, etc.. 
  * Helpers -> Functions
2. base.styl -> HTML5 Boilerplate + my generic styles (Uses core.styl)
  * Only html, no .classes or #ids
  * Required at my root component
3. Components -> Require within the component (uses core.styl)
  * Prints the component styles

So, hope it helps somehow!

Thaks!

**Comment by jossmac** [comment]
Just an update on this, it's looking like we'll go with http://projects.formidablelabs.com/radium

**Comment by nkbt** [comment]
Going with pure JS styles solution has noticeable downsides. As well as going old good css way. So far the best what worked out is a combination of https://github.com/css-modules/css-modules for purely visual styling and plain js styles for state-related styling.

But the problem we have here is packaging. We cannot rely on all consumers using Webpack. There are heaps of folks using bower, browserify, sprockets, plain old `<script>` tags. Real challenge is to find a universal solution that will not break existing developer's environment.

I definitely have some ideas how to solve this in a long term and will make some initial prototype hopefully quite soon.

**Comment by LorbusChris** [comment]
Have you heard about the myth css preprocessor? www.myth.io
Whats your opinion on that?
Its supposed to work like a CSS polyfill, and it uses the W3C proposed syntax for future versions of CSS.

**Comment by LorbusChris** [comment]
@jossmac could you clarify, please. are you going with radium or sticking with less? I'd personally favor radium now, but if you stick with less I will do the same. Thanks =)

**Comment by nkbt** [comment]
With this tool it is possible to use css modules.
https://www.npmjs.com/package/css-modules-require-hook

**Comment by jossmac** [comment]
@LorbusChris we'll likely transition the components to Radium when there's time, and like @TCMiranda mentioned leave CSS to do the things it's good at like resets, grids, etc.

The thing is we also maintain [KeystoneJS](https://github.com/keystonejs) and [TouchstoneJS](https://github.com/touchstonejs), not to mention the full-time commercial business [Thinkmill](http://thinkmill.com.au).

So if you're up for it we welcome pull requests, but otherwise please be patient :smile: 

* * *

N.B. this issues has been resolved so please continue any discussion related to CSS, LESS, Radium etc. over on #1

**Comment by LorbusChris** [comment]
sure thing! Thank you @nkbt @jossmac
