### ISSUE TITLE
Select box caret icon misplaced

### ISSUE THREAD

**Issue by MadRabbit** [elementalui/elemental#35]
Hey guys, thought you might wanna know. When validation on a select input fails, the caret icon shifts down (see the image)

![screen shot 2015-08-24 at 8 36 26 pm](https://cloud.githubusercontent.com/assets/14523/9438280/fb5fe8fe-4a9f-11e5-88cb-1ca49c8f94ca.png)

Cheers!

**Comment by jossmac** [comment]
Thanks for the heads up @MadRabbit
