### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by brunowego** [elementalui/elemental#41]
I wish contribute for a SASS version, have any plan for this or I can create a fork with this feature?

**Comment by jossmac** [comment]
@brunowego thanks for the offer!

We've actually had a great deal of trouble with styling components in Elemental and our other React.js projects with CSS (or pre-processor of choice). It's likely that we'll reimplement them using [Radium](http://projects.formidablelabs.com/radium). Is that something you'd be interested in?

**Comment by nkbt** [comment]
I would not bet on Radium, based on my gut feeling around css-modules, experience with js-only-styles and some other ideas around.
But you don't have to believe me of course just "because" and try it by yourself for at least 2-3 months on a scale.

**Comment by brunowego** [comment]
Nice to have an entire workflow based on a single technology. Based on this I will close this discussion.
