### ISSUE TITLE
missing common.js & bundle.js

### ISSUE THREAD

**Issue by xiongjiabin** [elementalui/elemental#43]
When I visit src/site or src/dist/ , missing common.js and bundle.js, 
I have no idea how to generate two files, I tried gulp build in the root of elemental.
Could you help out?

**Comment by nkbt** [comment]
Have you tried `npm run build`?

**Comment by xiongjiabin** [comment]
when run "npm run build" , has below errors :  
Browserify Error { [Error: Cannot find module 'blacklist' from '/home/tuanbowang/xueche/static/react/elemental']

**Comment by nkbt** [comment]
Have you run `npm install` before that? If yes, cleanup node_modules and
run again

**Comment by xiongjiabin** [comment]
done! Thanks!
