### ISSUE TITLE
touch capable range slider

### ISSUE THREAD

**Issue by medv** [elementalui/elemental#45]
Is something like this on the cards? http://refreshless.com/nouislider/

I'll have the need for it within a month, so if it's not making it into impending keystone0.4-related changes, let me know and I'll have a crack at it.

**Comment by jossmac** [comment]
Hi @medv!

That's a _little_ too specific for Elemental, but would be great as a standalone package, something like "react-range-slider". Which you could then use in Keystone as your own `fieldType`, or better yet submit it via PR for inclusion as a default field :)
