### ISSUE TITLE
Grid fixed width

### ISSUE THREAD

**Issue by mattapperson** [elementalui/elemental#48]
Sometimes ya just need a fixed width item in your grid (for a sidebar for example.

Thoughts on supporting this in the grid system and reflowing the width of non-fixed siblings?

**Comment by mattapperson** [comment]
NVM this does work its just not documented. I will close this and submit a PR for the docs.

**Comment by jossmac** [comment]
Hi @mattapperson, I'm not really sure what you mean. Would you mind trying to explain it? Perhaps with screenshots
