### ISSUE TITLE
add a dist folder in repository

### ISSUE THREAD

**Issue by Amomo** [elementalui/elemental#49]
Hello, I would like to add elemental to [cndjs](https://github.com/cdnjs/cdnjs) [(website)](https://cdnjs.com/) .

cdnjs has an auto-update mechanism to update libraries by git tags. 
It need to know a common path to add distributed files, it couldn't build the library.
So, I hope there have a `dist` folder to contain "elemental.css".

Would you please consider on adding a `dist` folder to collect the build file?

Thanks for your great work!! 😃

**Comment by nkbt** [comment]
There is a repo elemental-dist which has precompiled sources. Dist was
removed from this one.

Feel free to pr to that one! Thanks

**Comment by Amomo** [comment]
Oh, I find it! Thanks for your response. :-D
