### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by theolampert** [elementalui/elemental#5]
Looks like a really nice project, I'm wondering what the intended browser support is?.

**Comment by luisrudge** [comment]
It all works in windows phone 8.1. I'm impressed. Awesome work guys :)

**Comment by jossmac** [comment]
Hi @theolampert, great question!

We'd like Elemental to be viable (functionally and aesthetically) to as many browsers as possible, without hindering our ability to move quickly.

For now that means:
- Chrome (mobile and desktop)
- Safari (mobile and desktop)
- Firefox
- Internet Explorer 9 and up

**Comment by theolampert** [comment]
@jossmac thats great news, thanks for the feedback.

**Comment by JedWatson** [comment]
We should add this to the Readme & close this issue

**Comment by jossmac** [comment]
Updated the Readme in b05c8bd
