### ISSUE TITLE
FormSelect doesn't allow setting value

### ISSUE THREAD

**Issue by dmsnell** [elementalui/elemental#57]
I've been trying to programmatically set the value for the `<FormSelect />` component but have been having trouble doing so.

My first instinct is to the the `value` prop:

```js
<FormSelect options={ [...] } value={ selectedValue } />
```

Unfortunately this doesn't seem to do anything. I noticed in the source that `value` is blacklisted from the props for handing down to the `select` element. If I remove this from the blacklist, the value of the `select` gets appropriately updated.

Am I doing something wrong or is this a bug?

**Comment by jossmac** [comment]
Thanks for the heads up @dmsnell, I'll try to get a patch out today

**Comment by dmsnell** [comment]
thanks @jossmac !

**Comment by JedWatson** [comment]
I just released `v0.4.5` with this parch in it

**Comment by jossmac** [comment]
Cheers @JedWatson
