### ISSUE TITLE
arrows don't work in the datepicker

### ISSUE THREAD

**Issue by luisrudge** [elementalui/elemental#6]
![elemental](https://cloud.githubusercontent.com/assets/941075/7523893/d0737280-f4d4-11e4-8d37-b3c08adfa0a6.gif)

**Comment by jossmac** [comment]
Hi @luisrudge,

Thank you for taking the time to create this issue. We've since moved the date picker to its own repo where it is under development http://jedwatson.github.io/react-date-select
