### ISSUE TITLE
Pill does not show clear button after refactoring

### ISSUE THREAD

**Issue by MunGell** [elementalui/elemental#60]
Hi guys,

Looks like Pills will show clear button on them only when `onClear` function defined. Previously it was dependent on `showClearButton` flag.

So, as this flag is not used anywhere else, should we just remove it and update documentation or was it unintentional change in 9f0062b7053947257eb66e89ba57f2751fe42c56?

Thanks

**Comment by jossmac** [comment]
Resolved by 9c6ff58

**Comment by MunGell** [comment]
Thanks!
