### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by NogsMPLS** [elementalui/elemental#70]
Any plans on supporting React v0.14? (and react-router 1.0?)

Currently getting a lot of these
```Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.```

Should we open up a react 0.14 branch?

**Comment by zackify** [comment]
That's a pretty easy one to fix, I'll try starting a branch tonight.

**Comment by NogsMPLS** [comment]
yeah, I'm going about it right now actually. also noticed that only 2 components use 'react/addons' and they are both using css-transitions-group. I should have something up here in a little bit hopefully.

**Comment by NogsMPLS** [comment]
Got a PR in now that gets rid of all but 1 warning type in Elemental UI when using react 0.14 and react-router 1.0 release candidates. 

Would be nice to see this in a branch so we can prep switch over when RC goes official

**Comment by zackify** [comment]
I'll make a branch in a minute and accept your pull request

**Comment by NogsMPLS** [comment]
Awesome! Thanks for the fast merge, closing this now
