### ISSUE TITLE
Cannot find module 'react/addons' while using react-rails

### ISSUE THREAD

**Issue by gotjosh** [elementalui/elemental#73]
While using react-rails and properly turning `addons` on (double checked via `React.addons`) I keep getting a `Cannot find module 'react/addons'` error on the console despise react loading the `addons`.

Any ideas of where I should start looking for trouble? I'd gladly submit a PR if pointed in the right direction.

**Comment by nkbt** [comment]
There might be the case that react-rails dose not have a separate `addons` file in there, since it ships pre-built version of React.

I am not quite sure what should be the right solution though =(. Have zero experience with rails-*js-things*

**Comment by gotjosh** [comment]
You can configure `react-rails` to have the addons configured, I tried in all possible ways (including react from source with addons) and it still wouldn't work.

**Comment by JedWatson** [comment]
Unfortunately I have no experience using _rails-js-things_ either... @chantastic @zackify I believe you guys have some experience with Rails & React? any ideas on this one?

**Comment by chantastic** [comment]
I don't know much about the details of `react-rails`. @rmosolgo knows everything.

When you include `React` via `react-rails`, it's the `dist` version of React. `addons

**Comment by chantastic** [comment]
oops. submitted too soon... editing the previous answer.

**Comment by gotjosh** [comment]
I'm going to be doing some testing with browserify-rails, I'll keep you guys posted.

**Comment by JedWatson** [comment]
@gotjosh I just published an update for React 0.14, which now has `react-addons-css-transition-group` as a standalone package. So there's a very good chance that if you update to that, this problem will go away :)

**Comment by dbecker215** [comment]
I'm having the same issue, without Rails. It seems to be caused by the dependency on react-interval. I submitted an issue with react-interval because it says it should be compatible with 0.13 and 0.14, but a single "require('react-addons-pure-render-mixin')" on line 13 of ReactInterval.js seems to break it for us on 0.13. We were supposed to push to production this week at my company with 0.13 and this is causing a major breakage for us.

**Comment by jossmac** [comment]
Sorry you're having trouble @dbecker215

Just to be sure that we're on the same page, is your dependency on `react-interval` coming from Elemental?

**Comment by dbecker215** [comment]
Yes, I'm not using it directly. In the npm_modules for Elemental I have blacklist, classnames, and react-interval as dependencies.

**Comment by jossmac** [comment]
Okay great, if you update to the latest version (0.5.1) react-interval is no longer a requirement

**Comment by dbecker215** [comment]
That tell me that 0.5.1 requires 0.14. I was trying to avoid switching to 0.14 until we had more time at our company to test with it. Thanks though.

**Comment by jossmac** [comment]
0.4.7 or 0.4.8 will also work

**Comment by dbecker215** [comment]
@jossmac just got it back to working, thanks.
