### ISSUE TITLE
There should be a 'Getting Started...' page

### ISSUE THREAD

**Issue by SpencerCDixon** [elementalui/elemental#74]
Maybe this comes from me being super new to the JS/React community but there are no clear instructions on how to get this set up.  Problem I'm running into right now is how to get the css loaded.  Do I need to compile your less myself from node_modules using webpack/browserify? Seems hacky to me but maybe just because I'm spoiled from ruby gem ecosystem.

At the very least there should be a page like this: http://react-bootstrap.github.io/getting-started.html explaining that you need to npm install elemental, etc.

**Comment by NogsMPLS** [comment]
I agree, would be nice. Not everyone knows to immediately look in the package.json file for scripts.

**Comment by sahat** [comment]
:+1: For getting started page.

**Comment by JedWatson** [comment]
Just acknowledging this, it's something we'll do as soon as we've got time. If anyone wants to help contribute some content please give a shout out!

**Comment by topgun743** [comment]
Adding to this question: Can ElementalUI be used without using Node.js. I want to use it my web application that Asp.Net MVC based but can't figure out how to use it in there. Tried dist of ElementalUI on:
https://github.com/elementalui/elemental-dist 
but it fails upon not having certain dependencies which I guess require Node.js context. So is there anyway to use it without Node by simply having files added to page header?

**Comment by zenorocha** [comment]
+1

**Comment by zbyte64** [comment]
:+1:

**Comment by martinwh99** [comment]
+1

**Comment by iam-peekay** [comment]
@nogsmpls I'd love to hear how you went about including elemental in your project. I love the components but am lost on how to use it in my project

**Comment by NogsMPLS** [comment]
@iam-peekay It should be as simple as adding it in package.json and using/referencing it within your project. i.e.: ```import { Button } from 'elemental';```

One important note is that, currently, you will need a LESS compiler in your build process, and you will need to reference to the ```./node_modules/elemental/less/elemental.less``` file in your project some way so it can get compiled.

Or, alternatively, you could try grabbing the .js and .css files from https://github.com/elementalui/elemental-dist and using those. Though, that's not how I use the repo and am not sure what extra steps, if any, you would need to do. Also they seem to be a little outdated,running 0.5.3 and elemental is currently at 0.5.11.

**Comment by nathanvog** [comment]
+1

**Comment by n8sabes** [comment]
:+1:

**Comment by jossmac** [comment]
Getting Started info available on the [home page](https://github.com/elementalui/elemental/blob/373ac350a3c9e96b704a078fcf90d92a3a79910f/site/src/pages/Home.js#L62)
