### ISSUE TITLE
Setting Custom Width/Height and page position for Modal. How?

### ISSUE THREAD

**Issue by topgun743** [elementalui/elemental#78]
I have seen Elemental UI's demo. I have one concern.
How can we set custom width and height on Modal without using any third party dependency like CSS/jQuery/javascript etc.
And also similarly how can we position modal (top/left way) on page without using CSS/jQuery/Javascript etc?

**Comment by jossmac** [comment]
@topgun743 you make a good point!

**Comment by jossmac** [comment]
@topgun743 this will be in the next release. Thanks for the heads up

**Comment by topgun743** [comment]
Lovely. Where can I find a live preview now?

**Comment by topgun743** [comment]
Just saw your changes. Cool, Lovely. Thanks @jossmac
