### ISSUE TITLE
How to use ElementalUI in a simple website without using node.js?

### ISSUE THREAD

**Issue by topgun743** [elementalui/elemental#83]
I am trying to figure out how can I use ElementalUI in a simple website without using node.js?
I mean by simply adding js files to page head section and not through nodejs.
Is it possible? 
Tried dist of ElementalUI on:
    https://github.com/elementalui/elemental-dist
but it fails upon not having certain dependencies which I guess require Node.js context. So is there anyway to use it without Node by simply having files added to page header?

**Comment by nkbt** [comment]
Ah, I need to transfer my auto-publish script here at last! To publish automatically to bower.

But you don't have to have node-based project. You just need to have some build process for your frontend. Though if you don't have one at all, then Give me a little bit of time and elemental-dist will be up -to-date

**Comment by topgun743** [comment]
Thanks @nkbt for the reply. 
I am new to ElementalUI. Just want to use it along with ReactJS and I am not using nodejs. My project is simply Asp.Net MVC based. That's why asked you if it can be used straight away by adding to page header.
I can wait for your changes in Elemental-dist. Hope they will be soon. Thanks

**Comment by nkbt** [comment]
Ok, so you want to have pre-built dist then. I'm closing this in favor of #39, since you will have compiled lib there. If you don't mind, of course.
