### ISSUE TITLE
Dropdown component render bug in Safari

### ISSUE THREAD

**Issue by jonathanp** [elementalui/elemental#92]
The dropdown component has a render bug in Safari 9.0.1 on OS X. Check out the arrow in the screenshot below, it has a transparent pixel between the edges...

<img width="166" alt="screen shot 2015-11-10 at 16 13 35" src="https://cloud.githubusercontent.com/assets/76098/11075955/09b14fac-87c6-11e5-9e2c-4de4870c6ee2.png">

**Comment by jossmac** [comment]
Thanks for reporting this @jonathanp

Luckily it's limited to retina displays
