### ISSUE TITLE
Can't set ref to FormInput

### ISSUE THREAD

**Issue by danii1** [elementalui/elemental#94]
It seems you can't set custom `ref` to the FormInput because it overrides ref prop, thus we unable to reference form inputs by `this.refs.username.value` :
https://github.com/elementalui/elemental/blob/master/src/components/FormInput.js#L52

**Comment by danii1** [comment]
Besides it should be doable with ```autoFocus``` prop instead focusing manually

**Comment by zackify** [comment]
The new React Select does away with this as well. Wait for Jed to chime in
but I'm pretty sure he's moving towards 100% props based components. You
should store the state of inputs yourself and pass them to the input.

**Comment by danii1** [comment]
Component shouldn't break refs anyway, and you shouldn't enforce decision to store the state of the input.

**Comment by zackify** [comment]
If you take a look at the [docs on refs](https://facebook.github.io/react/docs/more-about-refs.html), they are not meant for this: "In most cases, this should be unnecessary because the reactive data flow always ensures that the most recent props are sent to each child that is output from render()." It is an antipattern to grab values through refs. I do agree it would be nice and I would like to see a way that doesn't overwrite a ref passed in as props.

**Comment by nkbt** [comment]
my thoughs on this: refs should be only used if you need to deal with some legacy or 3rd-party stuff. In properly written app there is no need for refs at all

**Comment by kof** [comment]
interesting ... also if we wrap components into higher order components, you can't access the ref that easily, you will need a callback.

I suggest to not to use string refs, but use a function, this way we can have the ref inside and also call the user ref function and pass the ref too.

**Comment by kof** [comment]
I have heard string refs will be deprecated in react anyways.

**Comment by danii1** [comment]
I agree that my example is not particularly good usage of refs(I used it for throwaway prototype with login form), I still use refs when testing components as they provide convenient access to DOM nodes. Anyway in this component ```ref``` was used to set focus for the input, I replaced this with supported by React ```autoFocus``` prop and removed ```ref``` overwrite.

**Comment by tkrotoff** [comment]
FYI
- material-ui has `inputRef` on all its components, see https://github.com/callemall/material-ui/blob/v1.0.0-beta.12/src/Input/Input.js#L255 and https://github.com/callemall/material-ui/search?utf8=%E2%9C%93&q=inputRef&type=
- reactstrap defines `getRef` (will be renamed `innerRef` in the future?), see https://github.com/reactstrap/reactstrap/issues/583
- React-Bootstrap defines `inputRef`, see https://github.com/react-bootstrap/react-bootstrap/blob/v0.31.3/src/Checkbox.js#L26
