### ISSUE TITLE
PhoneGap jank?

### ISSUE THREAD

**Issue by MMRandy** [elementalui/elemental#99]
Trying to use the Modal component in a PhoneGap app.  It works fine in the browser during testing, but when building via PhoneGap Build and testing on the device, the closing of the modal, along with the background overlay, do pretty strange things..flickering, changing size, etc..before finally closing.

Any ideas on this?  The code I used was pretty much copied form the Elemental Modal page verbatim.

Thanks.

**Comment by jossmac** [comment]
The [modal component](https://github.com/elementalui/elemental/blob/master/src/components/Modal.js) has a fairly unique composition compared to other components:
- It uses a portal to inject code into the DOM
- Accessibility enhancement for web use

I suspect the accessibility stuff is the culprit; recommend duplicating the component in your codebase and replacing the relevant sections to see how it effects your build. All that being said, PhoneGap does some wacky stuff sometimes...
